# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import os
import sys
from pathlib import Path


sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../src/"))

# -- Project information -----------------------------------------------------

from src.grovems._metadata import (
    __author__,
    __copyright__,
    __github_url__,
    __package__,
    __version__,
)

project = __package__
copyright = __copyright__
author = __author__

sys.path.insert(0, os.path.abspath(f"../src/{project}/"))

# The full version, including alpha/beta/rc tags

release = __version__

# Add to context for use in templates
html_context = {
    "display_github": True,  # Integrate GitHub
    "github_user": "wilhelm-lab",  # Username
    "github_repo": project,  # Repo name
    "github_version": release,  # Version
    "conf_py_path": "/docs/",  # Path in the checkout to the docs root
    "github_url": __github_url__,
}

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

extensions = [
    "sphinx.ext.napoleon",
    "sphinx.ext.autodoc",
    "sphinx_autodoc_typehints",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx_jinja",
]

jinja_contexts = {
    "project_info": {
        "project": project,
        "repo_url": __github_url__,
    }
}

autodoc_default_options = {"members": True, "undoc-members": False}

highlight_language = "pycon"

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#

html_theme = "sphinx_book_theme"

# book theme
html_theme_options = {
    "repository_url": __github_url__,
    "use_repository_button": True,
    # toc on the right side
    "show_toc_level": 1,
    "toc_title": "",
    "home_page_in_toc": True,
    # nav bar depth on the left
    "show_navbar_depth": 2,
    "path_to_docs": "docs/",
    "use_edit_page_button": True,
}

html_title = f"{project} | v{release}"
html_use_index = False  # Don't create index
html_domain_indices = False  # Don't need module indices
html_copy_source = False  # Don't need sources
html_permalinks = True
html_permalinks_icon = "🔗"
add_module_names = True
option_emphasise_placeholders = True
html_show_sphinx = False

autodoc_typehints = "description"
python_use_unqualified_type_names = True

autodoc_mock_imports = [
    "matplotlib",
    "numpy",
    "pandas",
    "pyod",
    "sklearn",
    "oktoberfest",
    "spectrum_fundamentals",
    "spectrum_io",
]

# -- Options for intersphinx mappings ----------------------------------

intersphinx_mapping = {
    "numpy": ("https://numpy.org/doc/stable/", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable/", None),
    "python": ("https://docs.python.org/3", None),
    "sklearn": ("https://scikit-learn.org/stable/", None),
}


# module path filter to create direct links to sources for autogenerated docs
# according to https://gist.github.com/flying-sheep/b65875c0ce965fbdd1d9e5d0b9851ef1


def get_obj_module(qualname):
    """Get a module/class/attribute and its original module by qualname."""
    modname = qualname
    classname = None
    attrname = None
    while modname not in sys.modules:
        attrname = classname
        modname, classname = modname.rsplit(".", 1)

    # retrieve object and find original module name
    if classname:
        cls = getattr(sys.modules[modname], classname)
        modname = cls.__module__
        obj = getattr(cls, attrname) if attrname else cls
    else:
        obj = None

    return obj, sys.modules[modname]


def get_linenos(obj):
    """Get an object’s line numbers."""
    try:
        lines, start = inspect.getsourcelines(obj)
    except TypeError:  # obj is an attribute or None
        return None, None
    else:
        return start, start + len(lines) - 1


project_dir = Path(__file__).parent.parent  # project/docs/conf.py/../.. → project/
github_url = "https://github.com/{github_user}/{github_repo}/tree/{github_version}".format_map(html_context)


def modurl(qualname):
    """Get the full GitHub URL for some object’s qualname."""
    obj, module = get_obj_module(qualname)
    path = Path(module.__file__).relative_to(project_dir)
    start, end = get_linenos(obj)
    fragment = f"#L{start}-L{end}" if start and end else ""
    return f"{github_url}/{path}{fragment}"


sitemap_url_scheme = "{link}"

# -- Options for autosectionlabel mappings -----------------------------
autosectionlabel_prefix_document = True
